[package]
name = "pallet-nexus"
version = "1.0.0"
edition = "2021"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
frame-system = { workspace = true, default-features = false }
avail-core = { workspace = true, default-features = false, features = [
	"runtime",
] }
avail-base = { workspace = true, default-features = false }

codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = [
	"derive",
] }
scale-info.workspace = true
frame-support = { workspace = true, default-features = false }
sp-io = { workspace = true, default-features = false }
sp-runtime = { workspace = true, default-features = false }
sp-std = { workspace = true, default-features = false }
sp-core = { workspace = true, default-features = false }
frame-benchmarking = { workspace = true, default-features = false, optional = true }

serde.workspace = true
serde_json.workspace = true
log.workspace = true
hex-literal.workspace = true
hex.workspace = true
rlp.workspace = true
primitive-types.workspace = true
ethabi.workspace = true
risc0-zkvm = { version = "1.2.0", default-features = false }
borsh = { version = "1.5.4", default-features = false, features = [
	"hashbrown",
] }

[dev-dependencies]
pallet-balances = { workspace = true, default-features = false, features = [
	"std",
] }
pallet-timestamp = { workspace = true, default-features = false }

[features]
default = ["std"]
std = [
	"avail-base/std",
	"avail-core/std",
	"codec/std",
	"frame-benchmarking?/std",
	"frame-support/std",
	"frame-system/std",
	"scale-info/std",
	"sp-core/std",
	"sp-io/std",
	"sp-runtime/std",
	"sp-std/std",
]
runtime-benchmarks = [
	"frame-benchmarking",
	"frame-benchmarking/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
]
try-runtime = [
	"frame-support/try-runtime",
	"frame-system/try-runtime",
	"sp-runtime/try-runtime",
]
