// This file is part of Data Availability.

// Copyright (C) 2021 Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Autogenerated weights for da_bridge
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2022-10-03, STEPS: `20`, REPEAT: 30, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 128

// Executed Command:
// ./target/release/data-avail
// benchmark
// --chain=dev
// --steps=20
// --repeat=30
// --log=warn
// --execution=wasm
// --wasm-execution=compiled
// --template=./.maintain/frame-weight-template.hbs
// --pallet=da-bridge
// --extrinsic=*
// --output=./pallets/nomad/da-bridge/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weight functions needed for da_bridge.
pub trait WeightInfo {
	fn try_dispatch_data_root() -> Weight;
}

/// Weights for da_bridge using the Data Avaiability node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	// Storage: System BlockHash (r:1 w:0)
	// Storage: NomadHome Base (r:1 w:0)
	// Storage: NomadHome Nonces (r:1 w:1)
	// Storage: NomadHome Tree (r:1 w:1)
	// Storage: NomadHome IndexToRoot (r:0 w:1)
	// Storage: NomadHome RootToIndex (r:0 w:1)
	fn try_dispatch_data_root() -> Weight {
		(93_524_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(4 as Weight))
			.saturating_add(T::DbWeight::get().writes(4 as Weight))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	// Storage: System BlockHash (r:1 w:0)
	// Storage: NomadHome Base (r:1 w:0)
	// Storage: NomadHome Nonces (r:1 w:1)
	// Storage: NomadHome Tree (r:1 w:1)
	// Storage: NomadHome IndexToRoot (r:0 w:1)
	// Storage: NomadHome RootToIndex (r:0 w:1)
	fn try_dispatch_data_root() -> Weight {
		(93_524_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(4 as Weight))
			.saturating_add(RocksDbWeight::get().writes(4 as Weight))
	}
}
