[package]
name = "system-rpc"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
avail-base.workspace = true
serde.workspace = true
jsonrpsee.workspace = true
sp-core.workspace = true
async-trait.workspace = true
frame-system-rpc-runtime-api.workspace = true
frame-system.workspace = true
hex.workspace = true
codec = { package = "parity-scale-codec", version = "3" }
sc-service.workspace = true
serde_json.workspace = true

[features]
default = [ "std" ]
std = [
	"avail-base/std",
	"serde/std",
	"sp-core/std",
]
