[workspace]

[package]
name = "insecure-connection"
edition = "2021"
version = "0.1.0"

[dependencies]
avail-rust = { path = "../../../." }
tokio = { version = "1.38.0", features = ["rt-multi-thread"] }
