binop_separator = "Back"
comment_width = 120
imports_granularity = "Crate"
max_width = 120
reorder_imports = true
tab_spaces = 4
trailing_semicolon = true
use_small_heuristics = "Max"
use_field_init_shorthand = true
wrap_comments = true
