// This file is part of Substrate.

// Copyright (C) Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Autogenerated weights for `pallet_fusion`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 32.0.0
//! DATE: 2024-12-19, STEPS: `10`, REPEAT: `5`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `DESKTOP-PAL18UV`, CPU: `AMD Ryzen 5 5600X 6-Core Processor`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: `1024`

// Executed Command:
// ./target/release/avail-node
// benchmark
// pallet
// --chain=dev
// --steps=10
// --repeat=5
// --pallet=pallet_fusion
// --extrinsic=*
// --heap-pages=4096
// --header=./HEADER-APACHE2
// --output=./pallets/weights.rs
// --template
// ./.maintain/frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_fusion`.
pub trait WeightInfo {
	fn create_currency() -> Weight;
	fn set_currency() -> Weight;
	fn destroy_currency() -> Weight;
	fn set_currency_conversion_rate() -> Weight;
	fn create_pool() -> Weight;
	fn set_pool() -> Weight;
	fn set_pool_with_retry(e: u32) -> Weight;
	fn destroy_pool() -> Weight;
	fn fill_pool_account() -> Weight;
	fn nominate() -> Weight;
	fn set_controller_address() -> Weight;
	fn set_slash_destination() -> Weight;
	fn update_max_tvl() -> Weight;
	fn set_compounding() -> Weight;
	fn stake() -> Weight;
	fn claim_rewards() -> Weight;
	fn unbond_currency() -> Weight;
	fn withdraw_unbonded_currency() -> Weight;
	fn withdraw_avail_to_controller() -> Weight;
	fn set_pool_boost_allocations() -> Weight;
	fn withdraw_pool_account() -> Weight;
	fn deposit_avail_to_fusion() -> Weight;
}

/// Weights for `pallet_fusion` using the Avail node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `Fusion::Currencies` (r:1 w:1)
	/// Proof: `Fusion::Currencies` (`max_values`: None, `max_size`: Some(127), added: 2602, mode: `MaxEncodedLen`)
	/// Storage: `Staking::ActiveEra` (r:1 w:0)
	/// Proof: `Staking::ActiveEra` (`max_values`: Some(1), `max_size`: Some(13), added: 508, mode: `MaxEncodedLen`)
	/// Storage: `Fusion::CurrencyRates` (r:0 w:1)
	/// Proof: `Fusion::CurrencyRates` (`max_values`: None, `max_size`: Some(40), added: 2515, mode: `MaxEncodedLen`)
	/// Storage: `Fusion::CurrencyRateChanges` (r:0 w:1)
	/// Proof: `Fusion::CurrencyRateChanges` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	fn create_currency() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `746`
		//  Estimated: `3592`
		// Minimum execution time: 23_073_000 picoseconds.
		Weight::from_parts(23_224_000, 3592)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `Fusion::Currencies` (r:1 w:1)
	/// Proof: `Fusion::Currencies` (`max_values`: None, `max_size`: Some(127), added: 2602, mode: `MaxEncodedLen`)
	fn set_currency() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `370`
		//  Estimated: `3592`
		// Minimum execution time: 13_215_000 picoseconds.
		Weight::from_parts(16_260_000, 3592)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Fusion::Pools` (r:1 w:0)
	/// Proof: `Fusion::Pools` (`max_values`: None, `max_size`: Some(14604742), added: 14607217, mode: `MaxEncodedLen`)
	/// Storage: `Fusion::Currencies` (r:1 w:1)
	/// Proof: `Fusion::Currencies` (`max_values`: None, `max_size`: Some(127), added: 2602, mode: `MaxEncodedLen`)
	/// Storage: `Fusion::CurrencyRateChanges` (r:0 w:1)
	/// Proof: `Fusion::CurrencyRateChanges` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	fn destroy_currency() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `370`
		//  Estimated: `14608207`
		// Minimum execution time: 18_896_000 picoseconds.
		Weight::from_parts(21_140_000, 14608207)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Fusion::Currencies` (r:1 w:0)
	/// Proof: `Fusion::Currencies` (`max_values`: None, `max_size`: Some(127), added: 2602, mode: `MaxEncodedLen`)
	/// Storage: `Fusion::CurrencyRateChanges` (r:0 w:1)
	/// Proof: `Fusion::CurrencyRateChanges` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	fn set_currency_conversion_rate() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `370`
		//  Estimated: `3592`
		// Minimum execution time: 13_976_000 picoseconds.
		Weight::from_parts(14_607_000, 3592)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Fusion::Pools` (r:1 w:1)
	/// Proof: `Fusion::Pools` (`max_values`: None, `max_size`: Some(14604742), added: 14607217, mode: `MaxEncodedLen`)
	/// Storage: `Fusion::Currencies` (r:1 w:0)
	/// Proof: `Fusion::Currencies` (`max_values`: None, `max_size`: Some(127), added: 2602, mode: `MaxEncodedLen`)
	/// Storage: `Fusion::PoolsAccountToId` (r:0 w:1)
	/// Proof: `Fusion::PoolsAccountToId` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	fn create_pool() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `370`
		//  Estimated: `14608207`
		// Minimum execution time: 19_125_000 picoseconds.
		Weight::from_parts(21_581_000, 14608207)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Fusion::Pools` (r:1 w:1)
	/// Proof: `Fusion::Pools` (`max_values`: None, `max_size`: Some(14604742), added: 14607217, mode: `MaxEncodedLen`)
	/// Storage: `Fusion::Currencies` (r:1 w:0)
	/// Proof: `Fusion::Currencies` (`max_values`: None, `max_size`: Some(127), added: 2602, mode: `MaxEncodedLen`)
	/// Storage: `Fusion::PoolsWithBoost` (r:0 w:1)
	/// Proof: `Fusion::PoolsWithBoost` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	fn set_pool() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `647`
		//  Estimated: `14608207`
		// Minimum execution time: 28_333_000 picoseconds.
		Weight::from_parts(30_467_000, 14608207)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Fusion::Pools` (r:1 w:1)
	/// Proof: `Fusion::Pools` (`max_values`: None, `max_size`: Some(14604742), added: 14607217, mode: `MaxEncodedLen`)
	/// Storage: `Fusion::Currencies` (r:1 w:0)
	/// Proof: `Fusion::Currencies` (`max_values`: None, `max_size`: Some(127), added: 2602, mode: `MaxEncodedLen`)
	/// Storage: `Fusion::EraDurations` (r:10 w:0)
	/// Proof: `Fusion::EraDurations` (`max_values`: None, `max_size`: Some(20), added: 2495, mode: `MaxEncodedLen`)
	/// Storage: `Fusion::Exposures` (r:20 w:0)
	/// Proof: `Fusion::Exposures` (`max_values`: None, `max_size`: Some(14601391), added: 14603866, mode: `MaxEncodedLen`)
	/// Storage: `Fusion::EraRewards` (r:10 w:10)
	/// Proof: `Fusion::EraRewards` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Fusion::PoolsWithBoost` (r:0 w:1)
	/// Proof: `Fusion::PoolsWithBoost` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// The range of component `e` is `[0, 10]`.
	fn set_pool_with_retry(e: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1850730 + e * (2900322 ±0)`
		//  Estimated: `14608207 + e * (29207732 ±0)`
		// Minimum execution time: 72_618_800_000 picoseconds.
		Weight::from_parts(73_665_302_277, 0)
			.saturating_add(Weight::from_parts(0, 14608207))
			// Standard Error: 226_110_695
			.saturating_add(Weight::from_parts(170_480_782_933, 0).saturating_mul(e.into()))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().reads((4_u64).saturating_mul(e.into())))
			.saturating_add(T::DbWeight::get().writes(2))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(e.into())))
			.saturating_add(Weight::from_parts(0, 29207732).saturating_mul(e.into()))
	}
	/// Storage: `Fusion::Pools` (r:1 w:1)
	/// Proof: `Fusion::Pools` (`max_values`: None, `max_size`: Some(14604742), added: 14607217, mode: `MaxEncodedLen`)
	/// Storage: `Staking::CurrentEra` (r:1 w:0)
	/// Proof: `Staking::CurrentEra` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:3 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Fusion::EraRewards` (r:1 w:0)
	/// Proof: `Fusion::EraRewards` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `Fusion::Exposures` (r:1 w:0)
	/// Proof: `Fusion::Exposures` (`max_values`: None, `max_size`: Some(14601391), added: 14603866, mode: `MaxEncodedLen`)
	/// Storage: `Fusion::ClaimedRewards` (r:1 w:0)
	/// Proof: `Fusion::ClaimedRewards` (`max_values`: None, `max_size`: Some(105), added: 2580, mode: `MaxEncodedLen`)
	/// Storage: `Fusion::PoolsAccountToId` (r:0 w:1)
	/// Proof: `Fusion::PoolsAccountToId` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `Fusion::PoolsWithBoost` (r:0 w:1)
	/// Proof: `Fusion::PoolsWithBoost` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	fn destroy_pool() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1587`
		//  Estimated: `14608207`
		// Minimum execution time: 84_318_000 picoseconds.
		Weight::from_parts(87_634_000, 14608207)
			.saturating_add(T::DbWeight::get().reads(8_u64))
			.saturating_add(T::DbWeight::get().writes(5_u64))
	}
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn fill_pool_account() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `280`
		//  Estimated: `6196`
		// Minimum execution time: 45_595_000 picoseconds.
		Weight::from_parts(46_417_000, 6196)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Fusion::Pools` (r:1 w:1)
	/// Proof: `Fusion::Pools` (`max_values`: None, `max_size`: Some(14604742), added: 14607217, mode: `MaxEncodedLen`)
	/// Storage: `Staking::Validators` (r:1 w:0)
	/// Proof: `Staking::Validators` (`max_values`: None, `max_size`: Some(45), added: 2520, mode: `MaxEncodedLen`)
	fn nominate() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1141`
		//  Estimated: `14608207`
		// Minimum execution time: 22_803_000 picoseconds.
		Weight::from_parts(23_324_000, 14608207)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Fusion::FusionAddressToSubstrateAddress` (r:1 w:1)
	/// Proof: `Fusion::FusionAddressToSubstrateAddress` (`max_values`: None, `max_size`: Some(113), added: 2588, mode: `MaxEncodedLen`)
	/// Storage: `Fusion::SlashDestination` (r:1 w:0)
	/// Proof: `Fusion::SlashDestination` (`max_values`: Some(1), `max_size`: Some(65), added: 560, mode: `MaxEncodedLen`)
	fn set_controller_address() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `285`
		//  Estimated: `3578`
		// Minimum execution time: 17_183_000 picoseconds.
		Weight::from_parts(18_514_000, 3578)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Fusion::SlashDestination` (r:0 w:1)
	/// Proof: `Fusion::SlashDestination` (`max_values`: Some(1), `max_size`: Some(65), added: 560, mode: `MaxEncodedLen`)
	/// Storage: `Fusion::FusionAddressToSubstrateAddress` (r:0 w:1)
	/// Proof: `Fusion::FusionAddressToSubstrateAddress` (`max_values`: None, `max_size`: Some(113), added: 2588, mode: `MaxEncodedLen`)
	fn set_slash_destination() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 16_350_000 picoseconds.
		Weight::from_parts(22_652_000, 0)
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Fusion::TotalValueLockedData` (r:1 w:1)
	/// Proof: `Fusion::TotalValueLockedData` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	fn update_max_tvl() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `200`
		//  Estimated: `1517`
		// Minimum execution time: 10_960_000 picoseconds.
		Weight::from_parts(11_651_000, 1517)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Fusion::FusionAddressToSubstrateAddress` (r:1 w:0)
	/// Proof: `Fusion::FusionAddressToSubstrateAddress` (`max_values`: None, `max_size`: Some(113), added: 2588, mode: `MaxEncodedLen`)
	/// Storage: `Fusion::Memberships` (r:1 w:1)
	/// Proof: `Fusion::Memberships` (`max_values`: None, `max_size`: Some(212), added: 2687, mode: `MaxEncodedLen`)
	/// Storage: `Fusion::Pools` (r:1 w:0)
	/// Proof: `Fusion::Pools` (`max_values`: None, `max_size`: Some(14604742), added: 14607217, mode: `MaxEncodedLen`)
	/// Storage: `Fusion::Currencies` (r:1 w:0)
	/// Proof: `Fusion::Currencies` (`max_values`: None, `max_size`: Some(127), added: 2602, mode: `MaxEncodedLen`)
	fn set_compounding() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `974`
		//  Estimated: `14608207`
		// Minimum execution time: 29_916_000 picoseconds.
		Weight::from_parts(30_547_000, 14608207)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Fusion::FusionAddressToSubstrateAddress` (r:1 w:0)
	/// Proof: `Fusion::FusionAddressToSubstrateAddress` (`max_values`: None, `max_size`: Some(113), added: 2588, mode: `MaxEncodedLen`)
	/// Storage: `Fusion::Pools` (r:1 w:1)
	/// Proof: `Fusion::Pools` (`max_values`: None, `max_size`: Some(14604742), added: 14607217, mode: `MaxEncodedLen`)
	/// Storage: `Fusion::Currencies` (r:1 w:1)
	/// Proof: `Fusion::Currencies` (`max_values`: None, `max_size`: Some(127), added: 2602, mode: `MaxEncodedLen`)
	/// Storage: `Fusion::Memberships` (r:1 w:1)
	/// Proof: `Fusion::Memberships` (`max_values`: None, `max_size`: Some(212), added: 2687, mode: `MaxEncodedLen`)
	/// Storage: `Fusion::UserCurrencyBalances` (r:1 w:1)
	/// Proof: `Fusion::UserCurrencyBalances` (`max_values`: None, `max_size`: Some(178), added: 2653, mode: `MaxEncodedLen`)
	/// Storage: `Fusion::TotalValueLockedData` (r:1 w:1)
	/// Proof: `Fusion::TotalValueLockedData` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `Staking::ActiveEra` (r:1 w:0)
	/// Proof: `Staking::ActiveEra` (`max_values`: Some(1), `max_size`: Some(13), added: 508, mode: `MaxEncodedLen`)
	/// Storage: `Fusion::CurrencyRates` (r:1 w:0)
	/// Proof: `Fusion::CurrencyRates` (`max_values`: None, `max_size`: Some(40), added: 2515, mode: `MaxEncodedLen`)
	/// Storage: `Staking::CurrentEra` (r:1 w:0)
	/// Proof: `Staking::CurrentEra` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn stake() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1851587`
		//  Estimated: `14608207`
		// Minimum execution time: 10_128_085_000 picoseconds.
		Weight::from_parts(10_401_957_000, 14608207)
			.saturating_add(T::DbWeight::get().reads(9_u64))
			.saturating_add(T::DbWeight::get().writes(5_u64))
	}
	/// Storage: `Fusion::Exposures` (r:1 w:0)
	/// Proof: `Fusion::Exposures` (`max_values`: None, `max_size`: Some(14601391), added: 14603866, mode: `MaxEncodedLen`)
	/// Storage: `Fusion::EraRewards` (r:1 w:1)
	/// Proof: `Fusion::EraRewards` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `Fusion::ClaimedRewards` (r:1 w:1)
	/// Proof: `Fusion::ClaimedRewards` (`max_values`: None, `max_size`: Some(105), added: 2580, mode: `MaxEncodedLen`)
	/// Storage: `Fusion::Currencies` (r:1 w:0)
	/// Proof: `Fusion::Currencies` (`max_values`: None, `max_size`: Some(127), added: 2602, mode: `MaxEncodedLen`)
	/// Storage: `Fusion::CurrencyRates` (r:1 w:0)
	/// Proof: `Fusion::CurrencyRates` (`max_values`: None, `max_size`: Some(40), added: 2515, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Fusion::UserCurrencyBalances` (r:1 w:1)
	/// Proof: `Fusion::UserCurrencyBalances` (`max_values`: None, `max_size`: Some(178), added: 2653, mode: `MaxEncodedLen`)
	/// Storage: `Fusion::Memberships` (r:1 w:0)
	/// Proof: `Fusion::Memberships` (`max_values`: None, `max_size`: Some(212), added: 2687, mode: `MaxEncodedLen`)
	fn claim_rewards() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2901240`
		//  Estimated: `14604856`
		// Minimum execution time: 5_073_252_000 picoseconds.
		Weight::from_parts(5_971_633_000, 14604856)
			.saturating_add(T::DbWeight::get().reads(9_u64))
			.saturating_add(T::DbWeight::get().writes(5_u64))
	}
	/// Storage: `Fusion::FusionAddressToSubstrateAddress` (r:1 w:0)
	/// Proof: `Fusion::FusionAddressToSubstrateAddress` (`max_values`: None, `max_size`: Some(113), added: 2588, mode: `MaxEncodedLen`)
	/// Storage: `Fusion::Memberships` (r:1 w:1)
	/// Proof: `Fusion::Memberships` (`max_values`: None, `max_size`: Some(212), added: 2687, mode: `MaxEncodedLen`)
	/// Storage: `Fusion::Pools` (r:1 w:1)
	/// Proof: `Fusion::Pools` (`max_values`: None, `max_size`: Some(14604742), added: 14607217, mode: `MaxEncodedLen`)
	/// Storage: `Fusion::Currencies` (r:1 w:1)
	/// Proof: `Fusion::Currencies` (`max_values`: None, `max_size`: Some(127), added: 2602, mode: `MaxEncodedLen`)
	/// Storage: `Staking::CurrentEra` (r:1 w:0)
	/// Proof: `Staking::CurrentEra` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Fusion::UnbondingChunks` (r:1 w:1)
	/// Proof: `Fusion::UnbondingChunks` (`max_values`: None, `max_size`: Some(8100028), added: 8102503, mode: `MaxEncodedLen`)
	/// Storage: `Fusion::HasBoost` (r:1 w:0)
	/// Proof: `Fusion::HasBoost` (`max_values`: None, `max_size`: Some(86), added: 2561, mode: `MaxEncodedLen`)
	/// Storage: `Fusion::TotalValueLockedData` (r:1 w:1)
	/// Proof: `Fusion::TotalValueLockedData` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `Staking::ActiveEra` (r:1 w:0)
	/// Proof: `Staking::ActiveEra` (`max_values`: Some(1), `max_size`: Some(13), added: 508, mode: `MaxEncodedLen`)
	/// Storage: `Fusion::CurrencyRates` (r:1 w:0)
	/// Proof: `Fusion::CurrencyRates` (`max_values`: None, `max_size`: Some(40), added: 2515, mode: `MaxEncodedLen`)
	fn unbond_currency() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1851914`
		//  Estimated: `14608207`
		// Minimum execution time: 10_508_795_000 picoseconds.
		Weight::from_parts(10_727_236_000, 14608207)
			.saturating_add(T::DbWeight::get().reads(10_u64))
			.saturating_add(T::DbWeight::get().writes(5_u64))
	}
	/// Storage: `Fusion::FusionAddressToSubstrateAddress` (r:1 w:0)
	/// Proof: `Fusion::FusionAddressToSubstrateAddress` (`max_values`: None, `max_size`: Some(113), added: 2588, mode: `MaxEncodedLen`)
	/// Storage: `Fusion::Memberships` (r:1 w:1)
	/// Proof: `Fusion::Memberships` (`max_values`: None, `max_size`: Some(212), added: 2687, mode: `MaxEncodedLen`)
	/// Storage: `Fusion::Pools` (r:1 w:1)
	/// Proof: `Fusion::Pools` (`max_values`: None, `max_size`: Some(14604742), added: 14607217, mode: `MaxEncodedLen`)
	/// Storage: `Fusion::Currencies` (r:1 w:1)
	/// Proof: `Fusion::Currencies` (`max_values`: None, `max_size`: Some(127), added: 2602, mode: `MaxEncodedLen`)
	/// Storage: `Staking::ActiveEra` (r:1 w:0)
	/// Proof: `Staking::ActiveEra` (`max_values`: Some(1), `max_size`: Some(13), added: 508, mode: `MaxEncodedLen`)
	/// Storage: `Fusion::UnbondingChunks` (r:1 w:1)
	/// Proof: `Fusion::UnbondingChunks` (`max_values`: None, `max_size`: Some(8100028), added: 8102503, mode: `MaxEncodedLen`)
	/// Storage: `Fusion::UserCurrencyBalances` (r:1 w:1)
	/// Proof: `Fusion::UserCurrencyBalances` (`max_values`: None, `max_size`: Some(178), added: 2653, mode: `MaxEncodedLen`)
	/// Storage: `Fusion::HasBoost` (r:1 w:1)
	/// Proof: `Fusion::HasBoost` (`max_values`: None, `max_size`: Some(86), added: 2561, mode: `MaxEncodedLen`)
	fn withdraw_unbonded_currency() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1851890`
		//  Estimated: `14608207`
		// Minimum execution time: 10_233_589_000 picoseconds.
		Weight::from_parts(10_510_839_000, 14608207)
			.saturating_add(T::DbWeight::get().reads(8_u64))
			.saturating_add(T::DbWeight::get().writes(6_u64))
	}
	/// Storage: `Fusion::FusionAddressToSubstrateAddress` (r:1 w:0)
	/// Proof: `Fusion::FusionAddressToSubstrateAddress` (`max_values`: None, `max_size`: Some(113), added: 2588, mode: `MaxEncodedLen`)
	/// Storage: `Fusion::Currencies` (r:1 w:0)
	/// Proof: `Fusion::Currencies` (`max_values`: None, `max_size`: Some(127), added: 2602, mode: `MaxEncodedLen`)
	/// Storage: `Fusion::UserCurrencyBalances` (r:1 w:1)
	/// Proof: `Fusion::UserCurrencyBalances` (`max_values`: None, `max_size`: Some(178), added: 2653, mode: `MaxEncodedLen`)
	/// Storage: `Staking::ActiveEra` (r:1 w:0)
	/// Proof: `Staking::ActiveEra` (`max_values`: Some(1), `max_size`: Some(13), added: 508, mode: `MaxEncodedLen`)
	/// Storage: `Fusion::CurrencyRates` (r:1 w:0)
	/// Proof: `Fusion::CurrencyRates` (`max_values`: None, `max_size`: Some(40), added: 2515, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn withdraw_avail_to_controller() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1498`
		//  Estimated: `6196`
		// Minimum execution time: 76_934_000 picoseconds.
		Weight::from_parts(77_445_000, 6196)
			.saturating_add(T::DbWeight::get().reads(7_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `Fusion::FusionAddressToSubstrateAddress` (r:1 w:0)
	/// Proof: `Fusion::FusionAddressToSubstrateAddress` (`max_values`: None, `max_size`: Some(113), added: 2588, mode: `MaxEncodedLen`)
	/// Storage: `Fusion::Memberships` (r:3 w:0)
	/// Proof: `Fusion::Memberships` (`max_values`: None, `max_size`: Some(212), added: 2687, mode: `MaxEncodedLen`)
	/// Storage: `Fusion::HasBoost` (r:2 w:0)
	/// Proof: `Fusion::HasBoost` (`max_values`: None, `max_size`: Some(86), added: 2561, mode: `MaxEncodedLen`)
	/// Storage: `Fusion::Currencies` (r:1 w:0)
	/// Proof: `Fusion::Currencies` (`max_values`: None, `max_size`: Some(127), added: 2602, mode: `MaxEncodedLen`)
	/// Storage: `Fusion::Pools` (r:1 w:0)
	/// Proof: `Fusion::Pools` (`max_values`: None, `max_size`: Some(14604742), added: 14607217, mode: `MaxEncodedLen`)
	/// Storage: `Fusion::PoolsWithBoost` (r:2 w:0)
	/// Proof: `Fusion::PoolsWithBoost` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	fn set_pool_boost_allocations() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1851275`
		//  Estimated: `14608207`
		// Minimum execution time: 3_011_833_000 picoseconds.
		Weight::from_parts(3_204_744_000, 14608207)
			.saturating_add(T::DbWeight::get().reads(10_u64))
	}
	/// Storage: `Fusion::Pools` (r:1 w:0)
	/// Proof: `Fusion::Pools` (`max_values`: None, `max_size`: Some(14604742), added: 14607217, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn withdraw_pool_account() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `837`
		//  Estimated: `14608207`
		// Minimum execution time: 51_737_000 picoseconds.
		Weight::from_parts(61_595_000, 14608207)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	fn deposit_avail_to_fusion() -> Weight {
		Weight::from_parts(10_000_000, 5000)
            .saturating_add(T::DbWeight::get().reads(3_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `Fusion::Currencies` (r:1 w:1)
	/// Proof: `Fusion::Currencies` (`max_values`: None, `max_size`: Some(127), added: 2602, mode: `MaxEncodedLen`)
	/// Storage: `Staking::ActiveEra` (r:1 w:0)
	/// Proof: `Staking::ActiveEra` (`max_values`: Some(1), `max_size`: Some(13), added: 508, mode: `MaxEncodedLen`)
	/// Storage: `Fusion::CurrencyRates` (r:0 w:1)
	/// Proof: `Fusion::CurrencyRates` (`max_values`: None, `max_size`: Some(40), added: 2515, mode: `MaxEncodedLen`)
	/// Storage: `Fusion::CurrencyRateChanges` (r:0 w:1)
	/// Proof: `Fusion::CurrencyRateChanges` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	fn create_currency() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `746`
		//  Estimated: `3592`
		// Minimum execution time: 23_073_000 picoseconds.
		Weight::from_parts(23_224_000, 3592)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `Fusion::Currencies` (r:1 w:1)
	/// Proof: `Fusion::Currencies` (`max_values`: None, `max_size`: Some(127), added: 2602, mode: `MaxEncodedLen`)
	fn set_currency() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `370`
		//  Estimated: `3592`
		// Minimum execution time: 13_215_000 picoseconds.
		Weight::from_parts(16_260_000, 3592)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `Fusion::Pools` (r:1 w:0)
	/// Proof: `Fusion::Pools` (`max_values`: None, `max_size`: Some(14604742), added: 14607217, mode: `MaxEncodedLen`)
	/// Storage: `Fusion::Currencies` (r:1 w:1)
	/// Proof: `Fusion::Currencies` (`max_values`: None, `max_size`: Some(127), added: 2602, mode: `MaxEncodedLen`)
	/// Storage: `Fusion::CurrencyRateChanges` (r:0 w:1)
	/// Proof: `Fusion::CurrencyRateChanges` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	fn destroy_currency() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `370`
		//  Estimated: `14608207`
		// Minimum execution time: 18_896_000 picoseconds.
		Weight::from_parts(21_140_000, 14608207)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `Fusion::Currencies` (r:1 w:0)
	/// Proof: `Fusion::Currencies` (`max_values`: None, `max_size`: Some(127), added: 2602, mode: `MaxEncodedLen`)
	/// Storage: `Fusion::CurrencyRateChanges` (r:0 w:1)
	/// Proof: `Fusion::CurrencyRateChanges` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	fn set_currency_conversion_rate() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `370`
		//  Estimated: `3592`
		// Minimum execution time: 13_976_000 picoseconds.
		Weight::from_parts(14_607_000, 3592)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `Fusion::Pools` (r:1 w:1)
	/// Proof: `Fusion::Pools` (`max_values`: None, `max_size`: Some(14604742), added: 14607217, mode: `MaxEncodedLen`)
	/// Storage: `Fusion::Currencies` (r:1 w:0)
	/// Proof: `Fusion::Currencies` (`max_values`: None, `max_size`: Some(127), added: 2602, mode: `MaxEncodedLen`)
	/// Storage: `Fusion::PoolsAccountToId` (r:0 w:1)
	/// Proof: `Fusion::PoolsAccountToId` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	fn create_pool() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `370`
		//  Estimated: `14608207`
		// Minimum execution time: 19_125_000 picoseconds.
		Weight::from_parts(21_581_000, 14608207)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `Fusion::Pools` (r:1 w:1)
	/// Proof: `Fusion::Pools` (`max_values`: None, `max_size`: Some(14604742), added: 14607217, mode: `MaxEncodedLen`)
	/// Storage: `Fusion::Currencies` (r:1 w:0)
	/// Proof: `Fusion::Currencies` (`max_values`: None, `max_size`: Some(127), added: 2602, mode: `MaxEncodedLen`)
	/// Storage: `Fusion::PoolsWithBoost` (r:0 w:1)
	/// Proof: `Fusion::PoolsWithBoost` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	fn set_pool() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `647`
		//  Estimated: `14608207`
		// Minimum execution time: 28_333_000 picoseconds.
		Weight::from_parts(30_467_000, 14608207)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `Fusion::Pools` (r:1 w:1)
	/// Proof: `Fusion::Pools` (`max_values`: None, `max_size`: Some(14604742), added: 14607217, mode: `MaxEncodedLen`)
	/// Storage: `Fusion::Currencies` (r:1 w:0)
	/// Proof: `Fusion::Currencies` (`max_values`: None, `max_size`: Some(127), added: 2602, mode: `MaxEncodedLen`)
	/// Storage: `Fusion::EraDurations` (r:10 w:0)
	/// Proof: `Fusion::EraDurations` (`max_values`: None, `max_size`: Some(20), added: 2495, mode: `MaxEncodedLen`)
	/// Storage: `Fusion::Exposures` (r:20 w:0)
	/// Proof: `Fusion::Exposures` (`max_values`: None, `max_size`: Some(14601391), added: 14603866, mode: `MaxEncodedLen`)
	/// Storage: `Fusion::EraRewards` (r:10 w:10)
	/// Proof: `Fusion::EraRewards` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Fusion::PoolsWithBoost` (r:0 w:1)
	/// Proof: `Fusion::PoolsWithBoost` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// The range of component `e` is `[0, 10]`.
	fn set_pool_with_retry(e: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1850730 + e * (2900322 ±0)`
		//  Estimated: `14608207 + e * (29207732 ±0)`
		// Minimum execution time: 72_618_800_000 picoseconds.
		Weight::from_parts(73_665_302_277, 0)
			.saturating_add(Weight::from_parts(0, 14608207))
			// Standard Error: 226_110_695
			.saturating_add(Weight::from_parts(170_480_782_933, 0).saturating_mul(e.into()))
			.saturating_add(RocksDbWeight::get().reads(2))
			.saturating_add(RocksDbWeight::get().reads((4_u64).saturating_mul(e.into())))
			.saturating_add(RocksDbWeight::get().writes(2))
			.saturating_add(RocksDbWeight::get().writes((1_u64).saturating_mul(e.into())))
			.saturating_add(Weight::from_parts(0, 29207732).saturating_mul(e.into()))
	}
	/// Storage: `Fusion::Pools` (r:1 w:1)
	/// Proof: `Fusion::Pools` (`max_values`: None, `max_size`: Some(14604742), added: 14607217, mode: `MaxEncodedLen`)
	/// Storage: `Staking::CurrentEra` (r:1 w:0)
	/// Proof: `Staking::CurrentEra` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:3 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Fusion::EraRewards` (r:1 w:0)
	/// Proof: `Fusion::EraRewards` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `Fusion::Exposures` (r:1 w:0)
	/// Proof: `Fusion::Exposures` (`max_values`: None, `max_size`: Some(14601391), added: 14603866, mode: `MaxEncodedLen`)
	/// Storage: `Fusion::ClaimedRewards` (r:1 w:0)
	/// Proof: `Fusion::ClaimedRewards` (`max_values`: None, `max_size`: Some(105), added: 2580, mode: `MaxEncodedLen`)
	/// Storage: `Fusion::PoolsAccountToId` (r:0 w:1)
	/// Proof: `Fusion::PoolsAccountToId` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `Fusion::PoolsWithBoost` (r:0 w:1)
	/// Proof: `Fusion::PoolsWithBoost` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	fn destroy_pool() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1587`
		//  Estimated: `14608207`
		// Minimum execution time: 84_318_000 picoseconds.
		Weight::from_parts(87_634_000, 14608207)
			.saturating_add(RocksDbWeight::get().reads(8_u64))
			.saturating_add(RocksDbWeight::get().writes(5_u64))
	}
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn fill_pool_account() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `280`
		//  Estimated: `6196`
		// Minimum execution time: 45_595_000 picoseconds.
		Weight::from_parts(46_417_000, 6196)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `Fusion::Pools` (r:1 w:1)
	/// Proof: `Fusion::Pools` (`max_values`: None, `max_size`: Some(14604742), added: 14607217, mode: `MaxEncodedLen`)
	/// Storage: `Staking::Validators` (r:1 w:0)
	/// Proof: `Staking::Validators` (`max_values`: None, `max_size`: Some(45), added: 2520, mode: `MaxEncodedLen`)
	fn nominate() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1141`
		//  Estimated: `14608207`
		// Minimum execution time: 22_803_000 picoseconds.
		Weight::from_parts(23_324_000, 14608207)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `Fusion::FusionAddressToSubstrateAddress` (r:1 w:1)
	/// Proof: `Fusion::FusionAddressToSubstrateAddress` (`max_values`: None, `max_size`: Some(113), added: 2588, mode: `MaxEncodedLen`)
	/// Storage: `Fusion::SlashDestination` (r:1 w:0)
	/// Proof: `Fusion::SlashDestination` (`max_values`: Some(1), `max_size`: Some(65), added: 560, mode: `MaxEncodedLen`)
	fn set_controller_address() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `285`
		//  Estimated: `3578`
		// Minimum execution time: 17_183_000 picoseconds.
		Weight::from_parts(18_514_000, 3578)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `Fusion::SlashDestination` (r:0 w:1)
	/// Proof: `Fusion::SlashDestination` (`max_values`: Some(1), `max_size`: Some(65), added: 560, mode: `MaxEncodedLen`)
	/// Storage: `Fusion::FusionAddressToSubstrateAddress` (r:0 w:1)
	/// Proof: `Fusion::FusionAddressToSubstrateAddress` (`max_values`: None, `max_size`: Some(113), added: 2588, mode: `MaxEncodedLen`)
	fn set_slash_destination() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 16_350_000 picoseconds.
		Weight::from_parts(22_652_000, 0)
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `Fusion::TotalValueLockedData` (r:1 w:1)
	/// Proof: `Fusion::TotalValueLockedData` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	fn update_max_tvl() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `200`
		//  Estimated: `1517`
		// Minimum execution time: 10_960_000 picoseconds.
		Weight::from_parts(11_651_000, 1517)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `Fusion::FusionAddressToSubstrateAddress` (r:1 w:0)
	/// Proof: `Fusion::FusionAddressToSubstrateAddress` (`max_values`: None, `max_size`: Some(113), added: 2588, mode: `MaxEncodedLen`)
	/// Storage: `Fusion::Memberships` (r:1 w:1)
	/// Proof: `Fusion::Memberships` (`max_values`: None, `max_size`: Some(212), added: 2687, mode: `MaxEncodedLen`)
	/// Storage: `Fusion::Pools` (r:1 w:0)
	/// Proof: `Fusion::Pools` (`max_values`: None, `max_size`: Some(14604742), added: 14607217, mode: `MaxEncodedLen`)
	/// Storage: `Fusion::Currencies` (r:1 w:0)
	/// Proof: `Fusion::Currencies` (`max_values`: None, `max_size`: Some(127), added: 2602, mode: `MaxEncodedLen`)
	fn set_compounding() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `974`
		//  Estimated: `14608207`
		// Minimum execution time: 29_916_000 picoseconds.
		Weight::from_parts(30_547_000, 14608207)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `Fusion::FusionAddressToSubstrateAddress` (r:1 w:0)
	/// Proof: `Fusion::FusionAddressToSubstrateAddress` (`max_values`: None, `max_size`: Some(113), added: 2588, mode: `MaxEncodedLen`)
	/// Storage: `Fusion::Pools` (r:1 w:1)
	/// Proof: `Fusion::Pools` (`max_values`: None, `max_size`: Some(14604742), added: 14607217, mode: `MaxEncodedLen`)
	/// Storage: `Fusion::Currencies` (r:1 w:1)
	/// Proof: `Fusion::Currencies` (`max_values`: None, `max_size`: Some(127), added: 2602, mode: `MaxEncodedLen`)
	/// Storage: `Fusion::Memberships` (r:1 w:1)
	/// Proof: `Fusion::Memberships` (`max_values`: None, `max_size`: Some(212), added: 2687, mode: `MaxEncodedLen`)
	/// Storage: `Fusion::UserCurrencyBalances` (r:1 w:1)
	/// Proof: `Fusion::UserCurrencyBalances` (`max_values`: None, `max_size`: Some(178), added: 2653, mode: `MaxEncodedLen`)
	/// Storage: `Fusion::TotalValueLockedData` (r:1 w:1)
	/// Proof: `Fusion::TotalValueLockedData` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `Staking::ActiveEra` (r:1 w:0)
	/// Proof: `Staking::ActiveEra` (`max_values`: Some(1), `max_size`: Some(13), added: 508, mode: `MaxEncodedLen`)
	/// Storage: `Fusion::CurrencyRates` (r:1 w:0)
	/// Proof: `Fusion::CurrencyRates` (`max_values`: None, `max_size`: Some(40), added: 2515, mode: `MaxEncodedLen`)
	/// Storage: `Staking::CurrentEra` (r:1 w:0)
	/// Proof: `Staking::CurrentEra` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn stake() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1851587`
		//  Estimated: `14608207`
		// Minimum execution time: 10_128_085_000 picoseconds.
		Weight::from_parts(10_401_957_000, 14608207)
			.saturating_add(RocksDbWeight::get().reads(9_u64))
			.saturating_add(RocksDbWeight::get().writes(5_u64))
	}
	/// Storage: `Fusion::Exposures` (r:1 w:0)
	/// Proof: `Fusion::Exposures` (`max_values`: None, `max_size`: Some(14601391), added: 14603866, mode: `MaxEncodedLen`)
	/// Storage: `Fusion::EraRewards` (r:1 w:1)
	/// Proof: `Fusion::EraRewards` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `Fusion::ClaimedRewards` (r:1 w:1)
	/// Proof: `Fusion::ClaimedRewards` (`max_values`: None, `max_size`: Some(105), added: 2580, mode: `MaxEncodedLen`)
	/// Storage: `Fusion::Currencies` (r:1 w:0)
	/// Proof: `Fusion::Currencies` (`max_values`: None, `max_size`: Some(127), added: 2602, mode: `MaxEncodedLen`)
	/// Storage: `Fusion::CurrencyRates` (r:1 w:0)
	/// Proof: `Fusion::CurrencyRates` (`max_values`: None, `max_size`: Some(40), added: 2515, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Fusion::UserCurrencyBalances` (r:1 w:1)
	/// Proof: `Fusion::UserCurrencyBalances` (`max_values`: None, `max_size`: Some(178), added: 2653, mode: `MaxEncodedLen`)
	/// Storage: `Fusion::Memberships` (r:1 w:0)
	/// Proof: `Fusion::Memberships` (`max_values`: None, `max_size`: Some(212), added: 2687, mode: `MaxEncodedLen`)
	fn claim_rewards() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2901240`
		//  Estimated: `14604856`
		// Minimum execution time: 5_073_252_000 picoseconds.
		Weight::from_parts(5_971_633_000, 14604856)
			.saturating_add(RocksDbWeight::get().reads(9_u64))
			.saturating_add(RocksDbWeight::get().writes(5_u64))
	}
	/// Storage: `Fusion::FusionAddressToSubstrateAddress` (r:1 w:0)
	/// Proof: `Fusion::FusionAddressToSubstrateAddress` (`max_values`: None, `max_size`: Some(113), added: 2588, mode: `MaxEncodedLen`)
	/// Storage: `Fusion::Memberships` (r:1 w:1)
	/// Proof: `Fusion::Memberships` (`max_values`: None, `max_size`: Some(212), added: 2687, mode: `MaxEncodedLen`)
	/// Storage: `Fusion::Pools` (r:1 w:1)
	/// Proof: `Fusion::Pools` (`max_values`: None, `max_size`: Some(14604742), added: 14607217, mode: `MaxEncodedLen`)
	/// Storage: `Fusion::Currencies` (r:1 w:1)
	/// Proof: `Fusion::Currencies` (`max_values`: None, `max_size`: Some(127), added: 2602, mode: `MaxEncodedLen`)
	/// Storage: `Staking::CurrentEra` (r:1 w:0)
	/// Proof: `Staking::CurrentEra` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Fusion::UnbondingChunks` (r:1 w:1)
	/// Proof: `Fusion::UnbondingChunks` (`max_values`: None, `max_size`: Some(8100028), added: 8102503, mode: `MaxEncodedLen`)
	/// Storage: `Fusion::HasBoost` (r:1 w:0)
	/// Proof: `Fusion::HasBoost` (`max_values`: None, `max_size`: Some(86), added: 2561, mode: `MaxEncodedLen`)
	/// Storage: `Fusion::TotalValueLockedData` (r:1 w:1)
	/// Proof: `Fusion::TotalValueLockedData` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `Staking::ActiveEra` (r:1 w:0)
	/// Proof: `Staking::ActiveEra` (`max_values`: Some(1), `max_size`: Some(13), added: 508, mode: `MaxEncodedLen`)
	/// Storage: `Fusion::CurrencyRates` (r:1 w:0)
	/// Proof: `Fusion::CurrencyRates` (`max_values`: None, `max_size`: Some(40), added: 2515, mode: `MaxEncodedLen`)
	fn unbond_currency() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1851914`
		//  Estimated: `14608207`
		// Minimum execution time: 10_508_795_000 picoseconds.
		Weight::from_parts(10_727_236_000, 14608207)
			.saturating_add(RocksDbWeight::get().reads(10_u64))
			.saturating_add(RocksDbWeight::get().writes(5_u64))
	}
	/// Storage: `Fusion::FusionAddressToSubstrateAddress` (r:1 w:0)
	/// Proof: `Fusion::FusionAddressToSubstrateAddress` (`max_values`: None, `max_size`: Some(113), added: 2588, mode: `MaxEncodedLen`)
	/// Storage: `Fusion::Memberships` (r:1 w:1)
	/// Proof: `Fusion::Memberships` (`max_values`: None, `max_size`: Some(212), added: 2687, mode: `MaxEncodedLen`)
	/// Storage: `Fusion::Pools` (r:1 w:1)
	/// Proof: `Fusion::Pools` (`max_values`: None, `max_size`: Some(14604742), added: 14607217, mode: `MaxEncodedLen`)
	/// Storage: `Fusion::Currencies` (r:1 w:1)
	/// Proof: `Fusion::Currencies` (`max_values`: None, `max_size`: Some(127), added: 2602, mode: `MaxEncodedLen`)
	/// Storage: `Staking::ActiveEra` (r:1 w:0)
	/// Proof: `Staking::ActiveEra` (`max_values`: Some(1), `max_size`: Some(13), added: 508, mode: `MaxEncodedLen`)
	/// Storage: `Fusion::UnbondingChunks` (r:1 w:1)
	/// Proof: `Fusion::UnbondingChunks` (`max_values`: None, `max_size`: Some(8100028), added: 8102503, mode: `MaxEncodedLen`)
	/// Storage: `Fusion::UserCurrencyBalances` (r:1 w:1)
	/// Proof: `Fusion::UserCurrencyBalances` (`max_values`: None, `max_size`: Some(178), added: 2653, mode: `MaxEncodedLen`)
	/// Storage: `Fusion::HasBoost` (r:1 w:1)
	/// Proof: `Fusion::HasBoost` (`max_values`: None, `max_size`: Some(86), added: 2561, mode: `MaxEncodedLen`)
	fn withdraw_unbonded_currency() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1851890`
		//  Estimated: `14608207`
		// Minimum execution time: 10_233_589_000 picoseconds.
		Weight::from_parts(10_510_839_000, 14608207)
			.saturating_add(RocksDbWeight::get().reads(8_u64))
			.saturating_add(RocksDbWeight::get().writes(6_u64))
	}
	/// Storage: `Fusion::FusionAddressToSubstrateAddress` (r:1 w:0)
	/// Proof: `Fusion::FusionAddressToSubstrateAddress` (`max_values`: None, `max_size`: Some(113), added: 2588, mode: `MaxEncodedLen`)
	/// Storage: `Fusion::Currencies` (r:1 w:0)
	/// Proof: `Fusion::Currencies` (`max_values`: None, `max_size`: Some(127), added: 2602, mode: `MaxEncodedLen`)
	/// Storage: `Fusion::UserCurrencyBalances` (r:1 w:1)
	/// Proof: `Fusion::UserCurrencyBalances` (`max_values`: None, `max_size`: Some(178), added: 2653, mode: `MaxEncodedLen`)
	/// Storage: `Staking::ActiveEra` (r:1 w:0)
	/// Proof: `Staking::ActiveEra` (`max_values`: Some(1), `max_size`: Some(13), added: 508, mode: `MaxEncodedLen`)
	/// Storage: `Fusion::CurrencyRates` (r:1 w:0)
	/// Proof: `Fusion::CurrencyRates` (`max_values`: None, `max_size`: Some(40), added: 2515, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn withdraw_avail_to_controller() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1498`
		//  Estimated: `6196`
		// Minimum execution time: 76_934_000 picoseconds.
		Weight::from_parts(77_445_000, 6196)
			.saturating_add(RocksDbWeight::get().reads(7_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `Fusion::FusionAddressToSubstrateAddress` (r:1 w:0)
	/// Proof: `Fusion::FusionAddressToSubstrateAddress` (`max_values`: None, `max_size`: Some(113), added: 2588, mode: `MaxEncodedLen`)
	/// Storage: `Fusion::Memberships` (r:3 w:0)
	/// Proof: `Fusion::Memberships` (`max_values`: None, `max_size`: Some(212), added: 2687, mode: `MaxEncodedLen`)
	/// Storage: `Fusion::HasBoost` (r:2 w:0)
	/// Proof: `Fusion::HasBoost` (`max_values`: None, `max_size`: Some(86), added: 2561, mode: `MaxEncodedLen`)
	/// Storage: `Fusion::Currencies` (r:1 w:0)
	/// Proof: `Fusion::Currencies` (`max_values`: None, `max_size`: Some(127), added: 2602, mode: `MaxEncodedLen`)
	/// Storage: `Fusion::Pools` (r:1 w:0)
	/// Proof: `Fusion::Pools` (`max_values`: None, `max_size`: Some(14604742), added: 14607217, mode: `MaxEncodedLen`)
	/// Storage: `Fusion::PoolsWithBoost` (r:2 w:0)
	/// Proof: `Fusion::PoolsWithBoost` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	fn set_pool_boost_allocations() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1851275`
		//  Estimated: `14608207`
		// Minimum execution time: 3_011_833_000 picoseconds.
		Weight::from_parts(3_204_744_000, 14608207)
			.saturating_add(RocksDbWeight::get().reads(10_u64))
	}
	/// Storage: `Fusion::Pools` (r:1 w:0)
	/// Proof: `Fusion::Pools` (`max_values`: None, `max_size`: Some(14604742), added: 14607217, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn withdraw_pool_account() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `837`
		//  Estimated: `14608207`
		// Minimum execution time: 51_737_000 picoseconds.
		Weight::from_parts(61_595_000, 14608207)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	fn deposit_avail_to_fusion() -> Weight {
		Weight::from_parts(10_000_000, 5000)
            .saturating_add(RocksDbWeight::get().reads(3_u64))
            .saturating_add(RocksDbWeight::get().writes(1u64))
	}
}