[package]
name = "avail-telemetry"
version = "0.1.0"
edition = "2021"

[dependencies]
sc-telemetry = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

tokio = { version = "1.43.0", features = ["sync"] }
