[package]
name = "transaction-rpc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
avail-base.workspace = true
serde.workspace = true
jsonrpsee.workspace = true
sp-core.workspace = true
async-trait.workspace = true

[features]
default = [ "std" ]
std = [
	"avail-base/std",
	"serde/std",
	"sp-core/std",
]
