[package]
name = "da-spammer"
version = "0.1.0"
edition = "2024"


[dependencies]
clap = { version = "4.5", features = ["derive"] }
tokio = { version = "1.45.1", features = ["macros", "rt-multi-thread"] }

avail-fri = { git = "https://github.com/availproject/avail-core.git", rev = "f1889544c65a7cf65df077bd4dc1e8941cd4e41f", default-features = false, features = [
    "parallel",
    "std",
] }
avail-rust = { package = "avail-rust-client", git = "https://github.com/availproject/avail-rust.git", rev = "88f6ac83e9b15b80d5a818083522e931ba9b1d60", default-features = false, features = [
    "native",
] }

sp-crypto-hashing = { version = "0.1.0", default-features = false }
codec = { package = "parity-scale-codec", version = "3", default-features = false, features = [
    "std",
] }

base64 = "0.22.1"
rayon = "1.11.0"
num_cpus = "1.17.0"
ctrlc = "3.5.1"
