[package]
name = "pallet-nomination-pools-benchmarking"
version = "1.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
description = "FRAME nomination pools pallet benchmarking"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
# parity
codec = { package = "parity-scale-codec", version = "3.6.1", default-features = false, features = ["derive"] }
scale-info = { version = "2.5.0", default-features = false, features = ["derive"] }

# FRAME
frame-benchmarking = { version = "4.0.0-dev", default-features = false }
frame-election-provider-support = { version = "4.0.0-dev", default-features = false }
frame-support = { version = "4.0.0-dev", default-features = false }
frame-system = { version = "4.0.0-dev", default-features = false }
pallet-bags-list = { version = "4.0.0-dev", default-features = false }
pallet-staking = { version = "4.0.0-dev", default-features = false }
pallet-nomination-pools = { version = "1.0.0", default-features = false, path = "../" }

# Substrate Primitives
sp-runtime = { version = "24.0.0", default-features = false }
sp-runtime-interface = { version = "17.0.0", default-features = false }
sp-staking = { version = "4.0.0-dev", default-features = false }
sp-std = { version = "8.0.0", default-features = false }

[dev-dependencies]
pallet-balances = { version = "4.0.0-dev", default-features = false }
pallet-timestamp = { version = "4.0.0-dev" }
pallet-staking-reward-curve = { version = "4.0.0-dev" }
sp-core = { version = "21.0.0" }
sp-io = { version = "23.0.0" }

[features]
default = ["std"]

std = [
	"frame-benchmarking/std",
	"frame-election-provider-support/std",
	"frame-support/std",
	"frame-system/std",
	"pallet-bags-list/std",
	"pallet-staking/std",
	"pallet-nomination-pools/std",
	"sp-runtime/std",
	"sp-runtime-interface/std",
	"sp-staking/std",
	"sp-std/std",
]

runtime-benchmarks = [
	"frame-election-provider-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"frame-benchmarking/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"sp-staking/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"pallet-staking/runtime-benchmarks",
	"pallet-nomination-pools/runtime-benchmarks",
	"pallet-bags-list/runtime-benchmarks",
]
