// This file is part of Substrate.

// Copyright (C) 2022 Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Autogenerated weights for da_control
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2023-06-30, STEPS: `50`, REPEAT: 25, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! HOSTNAME: `ip-172-31-39-104`, CPU: `Intel(R) Xeon(R) Platinum 8375C CPU @ 2.90GHz`
//! EXECUTION: Some(Native), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// ./target/release/data-avail
// benchmark
// pallet
// --chain=dev
// --steps=50
// --repeat=25
// --log=warn
// --execution=native
// --template=./.maintain/frame-weight-template.hbs
// --header=./HEADER-APACHE2
// --pallet=da-control
// --extrinsic=*
// --output=./pallets/dactr/src/weights.rs
// -linfo

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weight functions needed for da_control.
pub trait WeightInfo {
	fn create_application_key() -> Weight;
	fn submit_block_length_proposal() -> Weight;
	fn submit_data(i: u32, ) -> Weight;
	fn data_root(i: u32, ) -> Weight;
	fn commitment_builder_32(i: u32, ) -> Weight;
	fn commitment_builder_64(i: u32, ) -> Weight;
	fn commitment_builder_128(i: u32, ) -> Weight;
	fn commitment_builder_256(i: u32, ) -> Weight;
}

/// Weights for da_control using the Data Avaiability node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	// Storage: DataAvailability AppKeys (r:1 w:1)
	// Storage: DataAvailability NextAppId (r:1 w:1)
	fn create_application_key() -> Weight {
		// Minimum execution time: 18_206 nanoseconds.
		Weight::from_ref_time(18_647_000_u64)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	// Storage: System DynamicBlockLength (r:0 w:1)
	fn submit_block_length_proposal() -> Weight {
		// Minimum execution time: 12_680 nanoseconds.
		Weight::from_ref_time(12_902_000_u64)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// The range of component `i` is `[1, 524288]`.
	fn submit_data(i: u32, ) -> Weight {
		// Minimum execution time: 12_004 nanoseconds.
		Weight::from_ref_time(5_774_046_u64)
			// Standard Error: 0
			.saturating_add(Weight::from_ref_time(180_u64).saturating_mul(i as u64))
	}
	/// The range of component `i` is `[0, 524288]`.
	fn data_root(i: u32, ) -> Weight {
		// Minimum execution time: 375 nanoseconds.
		Weight::from_ref_time(392_000_u64)
			// Standard Error: 0
			.saturating_add(Weight::from_ref_time(801_u64).saturating_mul(i as u64))
	}
	/// The range of component `i` is `[32, 1024]`.
	fn commitment_builder_32(i: u32, ) -> Weight {
		// Minimum execution time: 968_552 nanoseconds.
		Weight::from_ref_time(1_006_887_000_u64)
			// Standard Error: 7_984_540
			.saturating_add(Weight::from_ref_time(50_376_469_u64).saturating_mul(i as u64))
	}
	/// The range of component `i` is `[32, 1024]`.
	fn commitment_builder_64(i: u32, ) -> Weight {
		// Minimum execution time: 961_762 nanoseconds.
		Weight::from_ref_time(1_008_376_000_u64)
			// Standard Error: 9_883_937
			.saturating_add(Weight::from_ref_time(595_118_242_u64).saturating_mul(i as u64))
	}
	/// The range of component `i` is `[32, 1024]`.
	fn commitment_builder_128(i: u32, ) -> Weight {
		// Minimum execution time: 971_907 nanoseconds.
		Weight::from_ref_time(1_024_232_000_u64)
			// Standard Error: 9_388_694
			.saturating_add(Weight::from_ref_time(972_044_283_u64).saturating_mul(i as u64))
	}
	/// The range of component `i` is `[32, 1024]`.
	fn commitment_builder_256(i: u32, ) -> Weight {
		// Minimum execution time: 981_799 nanoseconds.
		Weight::from_ref_time(103_127_562_903_u64)
			// Standard Error: 25_832_442
			.saturating_add(Weight::from_ref_time(1_382_474_182_u64).saturating_mul(i as u64))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	// Storage: DataAvailability AppKeys (r:1 w:1)
	// Storage: DataAvailability NextAppId (r:1 w:1)
	fn create_application_key() -> Weight {
		// Minimum execution time: 18_206 nanoseconds.
		Weight::from_ref_time(18_647_000_u64)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	// Storage: System DynamicBlockLength (r:0 w:1)
	fn submit_block_length_proposal() -> Weight {
		// Minimum execution time: 12_680 nanoseconds.
		Weight::from_ref_time(12_902_000_u64)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// The range of component `i` is `[1, 524288]`.
	fn submit_data(i: u32, ) -> Weight {
		// Minimum execution time: 12_004 nanoseconds.
		Weight::from_ref_time(5_774_046_u64)
			// Standard Error: 0
			.saturating_add(Weight::from_ref_time(180_u64).saturating_mul(i as u64))
	}
	/// The range of component `i` is `[0, 524288]`.
	fn data_root(i: u32, ) -> Weight {
		// Minimum execution time: 375 nanoseconds.
		Weight::from_ref_time(392_000_u64)
			// Standard Error: 0
			.saturating_add(Weight::from_ref_time(801_u64).saturating_mul(i as u64))
	}
	/// The range of component `i` is `[32, 1024]`.
	fn commitment_builder_32(i: u32, ) -> Weight {
		// Minimum execution time: 968_552 nanoseconds.
		Weight::from_ref_time(1_006_887_000_u64)
			// Standard Error: 7_984_540
			.saturating_add(Weight::from_ref_time(50_376_469_u64).saturating_mul(i as u64))
	}
	/// The range of component `i` is `[32, 1024]`.
	fn commitment_builder_64(i: u32, ) -> Weight {
		// Minimum execution time: 961_762 nanoseconds.
		Weight::from_ref_time(1_008_376_000_u64)
			// Standard Error: 9_883_937
			.saturating_add(Weight::from_ref_time(595_118_242_u64).saturating_mul(i as u64))
	}
	/// The range of component `i` is `[32, 1024]`.
	fn commitment_builder_128(i: u32, ) -> Weight {
		// Minimum execution time: 971_907 nanoseconds.
		Weight::from_ref_time(1_024_232_000_u64)
			// Standard Error: 9_388_694
			.saturating_add(Weight::from_ref_time(972_044_283_u64).saturating_mul(i as u64))
	}
	/// The range of component `i` is `[32, 1024]`.
	fn commitment_builder_256(i: u32, ) -> Weight {
		// Minimum execution time: 981_799 nanoseconds.
		Weight::from_ref_time(103_127_562_903_u64)
			// Standard Error: 25_832_442
			.saturating_add(Weight::from_ref_time(1_382_474_182_u64).saturating_mul(i as u64))
	}
}
