// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BlockInfo = { hash: string, height: number, };

export type ChainInfo = { best_hash: string, best_height: number, finalized_hash: string, finalized_height: number, genesis_hash: string, };

export type Error = { code: number, message: string, data: string | null, };

export type RpcRequestBlockInfo = { id: number, jsonrpc: string, method: string, params: [boolean], };

export type RpcRequestBlockNumber = { id: number, jsonrpc: string, method: string, params: [string], };

export type RpcRequestChainInfo = { id: number, jsonrpc: string, method: string, params: null, };

export type RpcResponseBlockInfo = { jsonrpc: string, result: BlockInfo | null, error: Error | null, id: number, };

export type RpcResponseBlockNumber = { jsonrpc: string, result: number | null, error: Error | null, id: number, };

export type RpcResponseChainInfo = { jsonrpc: string, result: ChainInfo | null, error: Error | null, id: number, };
