// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A phase of a block's execution.
 */
export type Phase = { "ApplyExtrinsic": number } | "Finalization" | "Initialization";
