[workspace]

[package]
name = "da-set-submit-data-fee-proposal"
edition = "2021"

[dependencies]
avail-rust = { path = "../../../../." }
tokio = { version = "1.38.0", features = ["rt-multi-thread"] }
