[package]
name = "da-commitment-js"
edition = "2021"
version = "0.1.0"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
avail-fri = { git = "https://github.com/availproject/avail-core.git", rev = "773b378836c9b75e5abf6f6f4c459572cdb28f6e", default-features = false }
wasm-bindgen = { version = "0.2" }
getrandom = { version = "0.2", features = ["js"] }
console_error_panic_hook = { version = "0.1" }
wasm-logger = { version = "0.2" }
log = "0.4.20"

[features]
default = ["std", "wasm"]
std = ["avail-fri/std"]
wasm = []
