name: Load

on: workflow_dispatch

jobs:
  load:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Copy scripts folder to remote server
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        source: "scripts/"
        target: "~/"
        overwrite: true

    - name: Run load tests
      uses: appleboy/ssh-action@master 
      with: 
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        command_timeout: "30m"
        script: |
          cd ~/scripts
          bash load-test.sh ${{ vars.VAL_COUNT }} ${{ vars.NODE_COUNT }} ${{ vars.LC_COUNT }} ${{ vars.TX_COUNT }} 
