[package]
name = "pallet-nomination-pools-fuzzer"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
description = "Fuzzer for fixed point arithmetic primitives."
documentation = "https://docs.rs/sp-arithmetic-fuzzer"
publish = false

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
honggfuzz = "0.5.54"

pallet-nomination-pools = { path = "..", features = ["fuzzing"] }

frame-system = { version = "4.0.0-dev" }
frame-support = { version = "4.0.0-dev" }

sp-runtime = { version = "24.0.0" }
sp-io = { version = "23.0.0" }
sp-tracing = { version = "10.0.0" }

rand = { version = "0.8.5", features = ["small_rng"] }
log = "0.4.17"

[[bin]]
name = "call"
path = "src/call.rs"
